Prepare gottcha2 for bioconda release
poeli/GOTTCHA2 pull request #6
Opened 2021-08-19 01:53 UTC by chernikovanna

- add database pull script
- package with setup.py

2021-08-19 19:36 UTC, poeli commented
Consider including `install_requires` in the setup.

Also, I suggest we should specify a package and an entry point for profiling and pulling databases, like [program] [command] [arguments]. For example:
>gottcha2 profile --help
>gottcha2 pull --help

How do you think?

2021-08-19 19:42 UTC, poeli requested changes
Suggest adding `install_requires` and provide commands instead of running separate scripts.

2021-08-20 00:44 UTC, chernikovanna commented
> Consider including `install_requires` in the setup.
> 
> Also, I suggest we should specify a package and an entry point for profiling and pulling databases, like [program] [command] [arguments]. For example:
> 
> > gottcha2 profile --help
> > gottcha2 pull --help
> 
> How do you think?

I think that's doable! I started building the entry point and I updated our CI but I have a bit more debugging to do.

2021-08-26 17:12 UTC, poeli-lanl commented on .github/workflows/gottcha.yml
> +          gottcha2 pull --help
test pulling a small gottcha_db database

2021-09-07 19:04 UTC, merged